CREATE TABLE BANK_ACCOUNT (
BANK_ID INT,
BANK_AMOUNT INT
);

CREATE TABLE INSURANCE_ACCOUNT (
INSURANCE_ID INT,
INSURANCE_AMOUNT INT
);

INSERT INTO BANK_ACCOUNT VALUES (1234, 500000);

INSERT INTO INSURANCE_ACCOUNT VALUES (5678, 100000);


